Add example using the ws281x-rpi driver
smart-leds-rs/smart-leds-samples pull request #13
Opened 2022-01-29 20:06 UTC by nathansamson

Add an example for Raspberry Pi using an alternative driver that allows full use of the std library and OS.

This is both intended as an example for people as a bit of (self) advertisement for this alternative driver.

2022-01-30 01:46 UTC, sajattack commented
Hmmm, why not just use linux-embedded-hal::spi and ws2812_spi?

2022-01-30 12:27 UTC, nathansamson commented
In all honesty... Because I could not get it to work :)  (note I used rppal but I think I would have the same issue).
Note that in the meantime I think I figured out what I probably did wrong and I could make this work.

That being said I still think its worth including this driver as reference + example as this driver is
A) Based on another driver that seems pretty popular (I found it by googling tutorials about connecting ws2812 to my raspberry pi). This means that problems people might have has quite a big community around it to solve issues (which sometimes you might need to convert to rust, but in some cases is just a OS configuration issue).

B) This driver gives 3 different modes (PCM, PWM, SPI) and gives users a bit more freedom. All modes have their own limitations. Admittedly SPI is the easier interface. (although previously mentioned tutorial uses PWM by default).


I hope this convinces you that this example is still worth it. If not I am probably going to create one based on either rppal and/or linux embedded hal as you suggested as I feel this might help other people as well figuring out how to make it work on a raspberry pi.

2022-01-30 12:43 UTC, david-sawatzke commented
I think this is a worthwhile addition and (after some testing) would like to merge it. The driver you've written also looks pretty good on a cursory overview, thank you.

Since this isn't using a `smart-leds` crate, please add a note to the readme that this example uses an external crate and is thus supported by the author (well, you). 

Adding a backend to (better) support non-baremetal targets to ws2812-spi is something I'd like to see in the future, but ws281x-rpi is more flexible on the rpi and is available right now.

2022-01-30 13:08 UTC, david-sawatzke requested changes
I think many people would want to build it on an x86 host instead of on the rpi (especially for the first, zero and zero w). A `.cargo/config` with the correct build target would help.

2022-01-30 13:08 UTC, david-sawatzke commented on raspberry-pi-ws281x-rpi-examples/src/lib.rs
> +#![no_std]
I don't think this file needs to exist

2022-01-30 13:12 UTC, david-sawatzke commented on raspberry-pi-ws281x-rpi-examples/src/lib.rs
> +#![no_std]
Sorry, my bad

2022-01-30 14:13 UTC, david-sawatzke commented
I'm giving up on crosscompiling the example: 
- Using arm-unknown-linux-gnueabihf on arch doesn't work
- Cross doesn't work
- Using zig also fails

Damm you, C!

2022-01-30 15:13 UTC, david-sawatzke commented
Seems to work pretty good on the raspberry pi one. After you change the README to note that this uses a third-party crate, I think this PR can be merged.

2022-01-30 21:49 UTC, david-sawatzke commented
FYI: I've made https://github.com/smart-leds-rs/ws2812-spi-rs/pull/27 as a pure-rust solution. Less tested and more limited pin-wise, may interest you.

That one can be crosscompiled using:
```
[build]
target = "arm-unknown-linux-musleabihf"
# rustup target add arm-unknown-linux-musleabihf


[target.arm-unknown-linux-musleabihf]
linker = "rust-lld"
```
But I'm pretty sure that would break ws281x-rpi.

Gonna have to look somewhat deeper in the cargo documentation or create a separate crate for the example.

It's not a blocker for this PR

2022-01-31 20:18 UTC, nathansamson commented
Updated the readme to clarify third-party status of driver used. (Just adding one word, if you think more is needed I'll add this :))

About cross-compile:
I did not mention any cross compile instructions as I figured out it would be too hard.
Also presumably users are using this with a Pi OS which should be more than capable enough of compiling rust applications in a decent amount of time and is less needed (eg when using the other rpi examples where it is being used in the boot sector you might not have an ARM device on hand, but in this use case people obviously do)

Thanks for working on the hosted variant, I might give that a try as well

2022-02-02 10:52 UTC, merged